version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rokagym
      POSTGRES_PASSWORD: cpekstlf1!
      POSTGRES_DB: rokagym
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
