version: "3"
services:
  nginx:
    image: nginx:alpine
    restart: always
    # network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/certs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro